@echo off
rem Nightly database backup for the dining counter PC.
rem Generated by the installer. Registered as the scheduled task "Dining DB backup".

rem The date comes from PowerShell rather than %DATE%, which is formatted per the machine's
rem regional settings -- the usual %DATE:~-4% trick produces a different string, sometimes an
rem invalid filename, on a differently-configured PC, and it fails silently.
for /f %%i in ('powershell -NoProfile -Command "Get-Date -Format yyyy-MM-dd_HHmm"') do set STAMP=%%i

set BK=C:\ProgramData\Dining\backup
set LOG=C:\ProgramData\Dining\logs\backup.log
set DUMP="%BK%\dining-%STAMP%.sql"

"C:\dining\runtime\mysql\bin\mysqldump.exe" --defaults-file="C:\dining\config\my.ini" ^
  -u root {{PWD_ARG}} --single-transaction --routines --events ^
  --default-character-set=utf8mb4 {{DB_NAME}} > %DUMP%

if errorlevel 1 (
  echo %DATE% %TIME% FAILED mysqldump returned an error >> "%LOG%"
  exit /b 1
)

rem A mysqldump that dies mid-stream still leaves a file behind. "We had backups" that turn out
rem to be 400-byte error headers is the classic way this goes wrong, so check the size.
for %%F in (%DUMP%) do if %%~zF LSS 10240 (
  echo %DATE% %TIME% FAILED dump only %%~zF bytes >> "%LOG%"
  exit /b 1
)

for %%F in (%DUMP%) do echo %DATE% %TIME% ok %%~zF bytes >> "%LOG%"

rem Keep 30 days. 2>nul swallows the "no files found" that forfiles prints in the first month.
forfiles /P "%BK%" /M dining-*.sql /D -30 /C "cmd /c del @path" 2>nul
exit /b 0
