; Dining counter configuration.
; Generated by the installer. Values here are kept in step with C:\dining\backend\.env -- if you
; change the database port or password, change it in BOTH or the counter stops issuing tokens.

[database]
host = 127.0.0.1
port = {{MYSQL_PORT}}
database = {{DB_NAME}}
user = root
password = {{DB_PASSWORD}}
; Every table in this database carries this prefix. It comes from DB_PREFIX in backend\.env,
; NOT from the default in config/database.php.
prefix = {{DB_PREFIX}}

[printer]
enabled = true
; Blank uses the Windows default printer.
name = {{PRINTER_NAME}}
copies = 1

[photos]
; Laravel's storage/app/public tree. files.file_path is resolved relative to this.
root = C:\dining\backend\storage\app\public
; Used when the file is not in that folder.
http_fallback = http://127.0.0.1:{{WEB_PORT}}/api/file/view/
; Nirmala ships with Windows and covers Bengali.
font = C:\Windows\Fonts\Nirmala.ttc

[app]
title = {{COUNTER_TITLE}}
; The users.id recorded as issued_by. Blank leaves it NULL, which is the honest record for a
; counter with no login.
issued_by =
fullscreen = true
result_seconds = 8
meal_poll_seconds = 60

; TESTING ONLY -- must be false on a counter that serves people.
; true prints a real receipt for every scan and writes NOTHING: no token, no token-number
; advance, no balance change, and the one-per-member-per-meal rule is not applied.
printer_test = false
