APP_NAME="College Dining"
APP_ENV=production

# Never regenerated by the installer. A restored production dump was written under this key, so
# rotating it here would silently invalidate anything encrypted with it.
APP_KEY={{APP_KEY}}

APP_DEBUG=false
APP_URL=http://localhost:{{WEB_PORT}}

LOG_CHANNEL=stack
LOG_LEVEL=warning

DB_CONNECTION=mysql_local_server
# 127.0.0.1, not localhost: on Windows "localhost" can resolve to ::1 first and add a failed
# connection attempt to every request.
DB_HOST=127.0.0.1
DB_PORT={{MYSQL_PORT}}
DB_DATABASE={{DB_NAME}}
DB_USERNAME=root
DB_PASSWORD={{DB_PASSWORD}}
# Every table carries this prefix. It comes from here and nowhere else -- the default in
# config/database.php is stale.
DB_PREFIX={{DB_PREFIX}}

BROADCAST_DRIVER=log
CACHE_DRIVER=file
FILESYSTEM_DISK=local
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

MAIL_MAILER=log
MAIL_FROM_ADDRESS="dining@localhost"
MAIL_FROM_NAME="${APP_NAME}"

UTIL_SERVER_URL='http://localhost:{{WEB_PORT}}/'
UTIL_SERVER_URL_PREFIX='util'

NCMS_API_URL='{{NCMS_URL}}'
NCMS_USERS_ENDPOINT='dining/users'
NCMS_IMAGE_BASE_URL='{{NCMS_IMAGE_URL}}'

# DEV-ONLY flag that makes any OTP code valid. Must stay false on a real machine.
MEMBER_OTP_BYPASS=false
SMS_DRIVER=log
