# Apache configuration for the dining counter PC.
# Generated by the installer from installer/templates/httpd-dining.conf.tpl.

ServerRoot "C:/dining/runtime/apache"

# Loopback only. The web admin is opened on this machine, by the person standing at it, through
# the "Dining Web Admin" shortcut. Binding to 127.0.0.1 is the actual enforcement -- a firewall
# rule would only ever have been a second line of defence, and there is deliberately no firewall
# rule for this port at all.
#
# Consequence to be aware of: member enrolment, meal prices, payments and reports can only be
# done AT the counter PC. Changing this to "Listen {{WEB_PORT}}" would expose it to the network
# again, and would also need a firewall rule to be of any use.
Listen 127.0.0.1:{{WEB_PORT}}
ServerName dining-counter:{{WEB_PORT}}
PidFile "C:/ProgramData/Dining/logs/httpd.pid"

# mpm_winnt is NOT loaded here: this Apache build compiles it statically into httpd.exe
# (confirmed with `httpd.exe -l`), so there is no modules/mod_mpm_winnt.so on disk and a
# LoadModule line for it fails at startup with "module not built in". The <IfModule mpm_winnt_module>
# block below still works without it -- Apache registers a compiled-in module under its module
# name the same as it would a loaded one, so the check still evaluates true.
LoadModule authz_core_module  modules/mod_authz_core.so
LoadModule dir_module         modules/mod_dir.so
LoadModule mime_module        modules/mod_mime.so
LoadModule rewrite_module     modules/mod_rewrite.so
LoadModule headers_module     modules/mod_headers.so
LoadModule expires_module     modules/mod_expires.so
LoadModule log_config_module  modules/mod_log_config.so
LoadModule deflate_module     modules/mod_deflate.so
LoadModule setenvif_module    modules/mod_setenvif.so
# AddOutputFilterByType below needs this loaded explicitly on this build; it is not part of core.
LoadModule filter_module      modules/mod_filter.so

# mod_php, not FastCGI. One Windows service, one process, real threading from mpm_winnt, and no
# third-party service wrapper anywhere. The DLL and the PHP build must come from the same VS
# toolset -- see installer/runtimes.lock.json before changing either.
LoadModule php_module "C:/dining/runtime/php/php8apache2_4.dll"
PHPIniDir "C:/dining/config"
AddHandler application/x-httpd-php .php

<IfModule mpm_winnt_module>
    ThreadsPerChild 64
    MaxConnectionsPerChild 0
</IfModule>

DocumentRoot "C:/dining/backend/public"

# index.php only, deliberately omitting index.html: "/" must reach Laravel's SpaController rather
# than be short-circuited by Apache serving the SPA shell directly.
DirectoryIndex index.php

<Directory "C:/dining/backend/public">
    Options -Indexes +FollowSymLinks
    # The repo's public/.htaccess already front-controls everything to index.php.
    AllowOverride All
    Require all granted
</Directory>

# Never serve application source, the env file, or database dumps, whatever else is misconfigured.
<DirectoryMatch "C:/dining/backend/(app|config|database|routes|storage|vendor|bootstrap|tests)">
    Require all denied
</DirectoryMatch>
<FilesMatch "^\.env">
    Require all denied
</FilesMatch>
<FilesMatch "\.(sql|ini|log|jsonl)$">
    Require all denied
</FilesMatch>

# The SPA build content-hashes every filename under /static, so these are safe to pin forever.
# The shell (index.html) is served by Laravel with no-store, so an upgrade is picked up on the
# next page load without a hard refresh.
<LocationMatch "^/static/">
    Header set Cache-Control "public, max-age=31536000, immutable"
</LocationMatch>

AddOutputFilterByType DEFLATE text/html text/css application/javascript application/json

ErrorLog  "C:/ProgramData/Dining/logs/apache-error.log"
CustomLog "C:/ProgramData/Dining/logs/apache-access.log" common
