# MySQL configuration for the dining counter PC.
# Generated by the installer from installer/templates/my.ini.tpl - edits here are overwritten
# on reinstall. Change it in C:\dining\config\my.ini instead.

[mysqld]
basedir  = C:/dining/runtime/mysql
datadir  = C:/ProgramData/Dining/mysql
port     = {{MYSQL_PORT}}

# The real access control. The counter app and Laravel both run on this machine, so nothing
# needs to reach the database over the network, and no firewall rule is ever opened for it.
bind-address = 127.0.0.1

# The counter app talks to MySQL through PyMySQL, which cannot do caching_sha2_password without
# the cryptography package. A blank root password happens to work either way, so pinning this
# matters the moment anyone sets a password: without it every scan fails with
# "cryptography is required for sha256_password". MySQL 8.4 removed this plugin, which is why
# the bundled server is pinned to 8.0.x.
default_authentication_plugin = mysql_native_password

character-set-server = utf8mb4
collation-server     = utf8mb4_unicode_ci

# Matches the server the production dump was taken from. ONLY_FULL_GROUP_BY off in particular:
# the reporting queries were written against a server that did not enforce it.
sql_mode = NO_ENGINE_SUBSTITUTION
explicit_defaults_for_timestamp = 1

# The Laravel app pins PHP to Asia/Dhaka, and the counter writes created_at using MySQL NOW(),
# so the server has to agree regardless of how the PC's clock is configured. A numeric offset,
# not a named zone: named zones need the timezone tables imported, which a portable install
# does not have.
default-time-zone = '+06:00'

# Restoring dining-full.sql sends very large single statements.
max_allowed_packet = 512M

innodb_buffer_pool_size = 512M

# Balances are money and nothing can re-derive them; do not relax this for speed.
innodb_flush_log_at_trx_commit = 1

table_open_cache = 512
skip-name-resolve
log-error = C:/ProgramData/Dining/logs/mysql-error.log

[client]
port = {{MYSQL_PORT}}
default-character-set = utf8mb4

[mysqldump]
quick
max_allowed_packet = 512M
default-character-set = utf8mb4
