; PHP configuration for the dining counter PC.
; Generated by the installer from installer/templates/php.ini.tpl.

extension_dir = "C:/dining/runtime/php/ext"

; Only what this application actually needs. Windows PHP 8.2 compiles ctype, tokenizer, json,
; the xml family, bcmath, iconv, session, filter, hash, pcre, phar and zlib into the binary, so
; they need no extension= line here.
extension=pdo_mysql     ; the database
extension=mbstring      ; laravel/framework
extension=openssl       ; APP_KEY encryption, tokens, TLS
extension=curl          ; guzzle -> the NCMS roster sync
extension=fileinfo      ; uploads and MIME detection
extension=gd            ; intervention/image, member photos
extension=zip           ; maatwebsite/excel, report exports
extension=exif          ; image orientation
extension=intl          ; date and number formatting
zend_extension=opcache

[opcache]
opcache.enable = 1
opcache.enable_cli = 0
opcache.memory_consumption = 192
opcache.max_accelerated_files = 20000
; Application files never change at runtime on this machine, so skip the per-request stat() of
; every file. NOTE: this means an upgrade MUST restart the DiningWeb service to take effect.
opcache.validate_timestamps = 0

date.timezone = Asia/Dhaka
memory_limit = 512M
upload_max_filesize = 32M
post_max_size = 40M

; The monthly and individual statement exports are genuinely slow on a full year of tokens.
max_execution_time = 300

display_errors = Off
log_errors = On
error_log = "C:/ProgramData/Dining/logs/php-error.log"
expose_php = Off
